### ISSUE TITLE
<jdbcUrl> not working

### ISSUE THREAD

**Issue by NoelVaes** [GeoDienstenCentrum/schemaspy-maven-plugin#166]
The configuration tag `<jdbcUrl>` is not working. It does not override the host address. It seems to be ignored.

* Maven version: 3.6.3
* Java version: 1.8
* Operating system and platform: Windows 10

**Comment by mprins** [comment]
Yes, the docs don't match with the functionality.
jdbcUrl has been ignored as an option for more than 10 years when there was an upgrade to SchemaSpy 5.0 (8f178ee5541a7477a4bb6c480d41fd2b89ea3586)

it would require extra code in https://github.com/GeoDienstenCentrum/schemaspy-maven-plugin/blob/master/src/main/java/com/wakaleo/schemaspy/util/JDBCHelper.java to parse the host (and port etc.) from the url and the pass those back the Report MoJo somewhere here: https://github.com/GeoDienstenCentrum/schemaspy-maven-plugin/blob/9c22fd56c9387d7bf21ec21ce442da4aafb8246b/src/main/java/com/wakaleo/schemaspy/SchemaSpyReport.java#L413-L449
