### ISSUE TITLE
Support running from CLI

### ISSUE THREAD

**Issue by marcelstoer** [GeoDienstenCentrum/schemaspy-maven-plugin#200]
### Expected Behavior

Allow to run and configure the plugin from the command line. Example: 

```
$  mvn nl.geodienstencentrum.maven:schemaspy-maven-plugin:5.1.0:schemaspy -DdatabaseType=pgsql -Dhost=localhost -Dport=5432 -Ddatabase=test -Duser=testuser -Dpassword=testuser -DoutputDirectory=/tmp

```

### Actual Behavior

> [ERROR] Failed to execute goal nl.geodienstencentrum.maven:schemaspy-maven-plugin:5.1.0:schemaspy (default-cli) on project myproject: The parameters 'database' for goal nl.geodienstencentrum.maven:schemaspy-maven-plugin:5.1.0:schemaspy are missing or invalid 

### Required Changes

If I'm not mistaken all `@Parameter` annotations in [SchemaSpyReport.java](https://github.com/GeoDienstenCentrum/schemaspy-maven-plugin/blob/master/src/main/java/com/wakaleo/schemaspy/SchemaSpyReport.java#L75) need a `property` attribute.

**Comment by marcelstoer** [comment]
> If I'm not mistaken

I wasn't 😄 -> #201

**Comment by mprins** [comment]
yes, this was not a forseen use case
